version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: fastapidb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:    
      - db_data:/var/lib/mysql
      
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: fastapidb
      DB_USER: user
      DB_PASS: secret
    volumes:
      - .:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      
volumes:
  db_data:
